# Task definition for the gcs_to_bigquery_bronze Cloud Run Job.
description: Download scraped data from GCS and load into BigQuery to create bronze layer.
type: python
machine:
  cpu: "1"
  memory: 512Mi
  timeout: 1800s
retry:
  repetitions: 0
entrypoint: app.entrypoints.gcs_to_bigquery_bronze
inputs:
  parameters:
    - name: ENVIRONMENT
      default: dev
    - name: CITY
      default: macae
    - name: SITES
      default: vivareal,zapimoveis
    - name: PROPERTY_TYPES
      default: apartment,house
    - name: FILE_DATE
      default: ""
    - name: UPLOAD_TO_BQ
      default: true
    - name: START_PAGE
      default: 1
    - name: MAX_PAGE
      default: -1
